# Dockerfile.dev
FROM node:23-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy entire project (including entrypoint.sh)
COPY . .

# Ensure script is executable inside container
RUN chmod +x /app/entrypoint.sh

EXPOSE 3000

# Run the entrypoint script
ENTRYPOINT ["/app/entrypoint.sh"]
