version: '3.8'

services:
  db:
    image: postgres:17.0-alpine
    container_name: rah_pg
    environment:     
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data    
    networks:
      - rah-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rah_nextjs
    ports:
      - "3000:3000"    
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      NODE_ENV: production
    networks:
      - rah-network
volumes:
  pg_data:
networks:
  rah-network:
